max_characters = 2000
themes = ['Love', 'Desire', 'Heartache & Loss', 'Realistic & Complicated', 'Romantic Love',
         'Classic Love', 'Infatuation & Crushes', 'Unrequited Love', 'Break-ups & Vexed Love',
         'First Love', 'Nature', 'Winter', 'Spring', 'Summer', 'Fall', 'Landscapes & Pastorals',
         'Weather', 'Trees & Flowers', 'Stars, Planets, Heavens', 'Seas, Rivers, & Streams',
         'Animals', 'Social Commentaries', 'History & Politics', 'War & Conflict', 'Crime & Punishment',
         'Money & Economics', 'Race & Ethnicity', 'Gender & Sexuality', 'Class', 'Popular Culture',
         'Cities & Urban Life', 'Town & Country Life', 'Religion', 'Faith & Doubt', 'God & the Divine',
         'Judaism', 'Buddhism', 'Islam', 'Christianity', 'Other Religions', 'The Spiritual', 'Living',
         'Birth & Birthdays', 'Infancy', 'Youth', 'Coming of Age', 'Marriage & Companionship',
         'Parenthood', 'Separation & Divorce', 'Midlife', 'Growing Old', 'Health & Illness',
         'Disappointment & Failure', 'Death', 'Sorrow & Grieving', 'Life Choices', 'The Body',
         'The Mind', 'Time & Brevity', 'Relationships', 'Men & Women', 'Friends & Enemies',
         'Gay, Lesbian, Queer', 'Home Life', 'Family & Ancestors', 'Pets', 'Activities',
         'School & Learning', 'Jobs & Working', 'Travels & Journeys', 'Sports & Outdoor Activities',
         'Gardening', 'Eating & Drinking', 'Indoor Activities', 'Arts & Sciences', 'Philosophy',
         'Sciences', 'Reading & Books', 'Poetry & Poets', 'Humor & Satire', 'Music', 'Theater & Dance',
         'Painting & Sculpture', 'Architecture & Design', 'Photography & Film', 'Language & Linguistics',
         'Mythology & Folklore', 'Ghosts & the Supernatural', 'Horror', 'Heroes & Patriotism',
         'Greek & Roman Mythology', 'Fairy-tales & Legends']
