max_characters = 2000
themes = ['love', 'desire', 'heartache & loss', 'realistic & complicated', 'romantic love',
         'classic love', 'infatuation & crushes', 'unrequited love', 'break-ups & vexed love',
         'first love', 'nature', 'winter', 'spring', 'summer', 'fall', 'landscapes & pastorals',
         'weather', 'trees & flowers', 'stars, planets, heavens', 'seas, rivers, & streams',
         'animals', 'social commentaries', 'history & politics', 'war & conflict', 'crime & punishment',
         'money & economics', 'race & ethnicity', 'gender & sexuality', 'class', 'popular culture',
         'cities & urban life', 'town & country life', 'religion', 'faith & doubt', 'god & the divine',
         'judaism', 'buddhism', 'islam', 'christianity', 'other religions', 'the spiritual', 'living',
         'birth & birthdays', 'infancy', 'youth', 'coming of age', 'marriage & companionship',
         'parenthood', 'separation & divorce', 'midlife', 'growing old', 'health & illness',
         'disappointment & failure', 'death', 'sorrow & grieving', 'life choices', 'the body',
         'the mind', 'time & brevity', 'relationships', 'men & women', 'friends & enemies',
         'gay, lesbian, queer', 'home life', 'family & ancestors', 'pets', 'activities',
         'school & learning', 'jobs & working', 'travels & journeys', 'sports & outdoor activities',
         'gardening', 'eating & drinking', 'indoor activities', 'arts & sciences', 'philosophy',
         'sciences', 'reading & books', 'poetry & poets', 'humor & satire', 'music', 'theater & dance',
         'painting & sculpture', 'architecture & design', 'photography & film', 'language & linguistics',
         'mythology & folklore', 'ghosts & the supernatural', 'horror', 'heroes & patriotism',
         'greek & roman mythology', 'fairy-tales & legends']
